

model_config:
  vocab_size: 512
  d_model: 8
  heads: 8

data_gen_config:
  min_len: 1
  max_len: 10
  sentences_per_example: 10
  examples_per_batch: 10

train_config:
  checkpoint_folder: "checkpoints"
  num_steps: 1000

optim:
  lr: 1e-3